// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWCovudvvRlURfqtNf-LjwsfEJpFFzW3o',
    appId: '1:907490520038:web:0f0963f63323dc77bbc427',
    messagingSenderId: '907490520038',
    projectId: 'tp5-dap-bcd7f',
    authDomain: 'tp5-dap-bcd7f.firebaseapp.com',
    storageBucket: 'tp5-dap-bcd7f.firebasestorage.app',
    measurementId: 'G-8Z0BXJWDJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDfSFhZ7AM_bca0-1PMEkua75KxiUk8iM',
    appId: '1:907490520038:android:f7c7e71a7ff7975fbbc427',
    messagingSenderId: '907490520038',
    projectId: 'tp5-dap-bcd7f',
    storageBucket: 'tp5-dap-bcd7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB7VGmBmvmiy65mgtAozenDChKd6T0cUk',
    appId: '1:907490520038:ios:db95deaeee4c1438bbc427',
    messagingSenderId: '907490520038',
    projectId: 'tp5-dap-bcd7f',
    storageBucket: 'tp5-dap-bcd7f.firebasestorage.app',
    iosBundleId: 'com.example.tp5Dap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB7VGmBmvmiy65mgtAozenDChKd6T0cUk',
    appId: '1:907490520038:ios:db95deaeee4c1438bbc427',
    messagingSenderId: '907490520038',
    projectId: 'tp5-dap-bcd7f',
    storageBucket: 'tp5-dap-bcd7f.firebasestorage.app',
    iosBundleId: 'com.example.tp5Dap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWCovudvvRlURfqtNf-LjwsfEJpFFzW3o',
    appId: '1:907490520038:web:69ad94e153485741bbc427',
    messagingSenderId: '907490520038',
    projectId: 'tp5-dap-bcd7f',
    authDomain: 'tp5-dap-bcd7f.firebaseapp.com',
    storageBucket: 'tp5-dap-bcd7f.firebasestorage.app',
    measurementId: 'G-SM6ZX4G253',
  );
}
